"""Add order_type and status to invoices

Revision ID: 4dd69935274c
Revises: becf559b6b0c
Create Date: 2025-09-21 15:02:18.755738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd69935274c'
down_revision = 'becf559b6b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_invoice', schema=None) as batch_op:
        # We add server_default to give existing rows a value
        batch_op.add_column(sa.Column('order_type', sa.String(length=20), nullable=False, server_default='In-Store'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Approved'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_invoice', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('order_type')

    # ### end Alembic commands ###
