"""Final database sync

Revision ID: d48a463ee864
Revises: 
Create Date: 2025-08-16 18:41:58.714719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48a463ee864'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_invoice', schema=None) as batch_op:
        batch_op.drop_column('gst')
        batch_op.drop_column('ptr')

    with op.batch_alter_table('customer_invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ptr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_invoice_item', schema=None) as batch_op:
        batch_op.drop_column('gst')
        batch_op.drop_column('ptr')

    with op.batch_alter_table('customer_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ptr', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gst', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
